main:
  - name: Accueil
    url: /
    weight: 10

  - name: Recherche
    url: /projects/
    weight: 20

  - name: Publications
    url: /publications/
    weight: 30

  - name: Enseignement
    url: /courses/
    weight: 40

  - name: CV
    url: /experience/
    weight: 50

  - name: Contact
    url: /#contact
    weight: 60

